In [70]:
import numpy as np
from matplotlib.pyplot import *
import scipy.linalg

In [71]:
def count_connections (filename):
    with open(filename,"r") as f:
        connections={}
        for line in f:
            if line.startswith("#") or line.startswith("Source"):
                continue
            connections.setdefault(line.split()[0],[0,0])
            connections.setdefault(line.split()[1],[0,0])

            connections[line.split()[0]][1]+=1
            connections[line.split()[1]][0]+=1

    return connections 

In [72]:
def build_adj_list(filename, gene_list):
    with open(filename,"r") as f:
        adj_matrix=np.zeros((len(gene_list),len(gene_list)))
        for line in f:
            if line.startswith("#") or line.startswith("Source"):
                continue
            
            source=gene_list.index(line.split()[0])
            target=gene_list.index(line.split()[1])
    
            if line.split()[2] == "+":
                adj_matrix[target][source]=1 
            elif line.split()[2] == "-":
                adj_matrix[target][source]=-1 
                
    return adj_matrix

In [73]:
gene_list=[key for key in count_connections("pruned_net.csv").keys()]


matrix=build_adj_list("pruned_net.csv", gene_list)
print(matrix)

[[ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0. -1. -1.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  1.]
 [ 0.  0. -1. -1.  0.  0.  0.  0. -1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [77]:
rhoW0 = max(abs(scipy.linalg.eig(matrix)[0]))
norm_matrix= (0.95/rhoW0)*matrix
print(norm_matrix)

[[ 0.    0.    0.    0.    0.    0.    0.    0.   -0.95  0.    0.    0.
   0.95]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.95]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.95]
 [ 0.    0.95  0.    0.    0.    0.    0.    0.   -0.95 -0.95  0.    0.
   0.95]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.95]
 [ 0.    0.    0.    0.    0.    0.   -0.95  0.    0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.95  0.    0.    0.    0.    0.    0.    0.  ]
 [ 0.95  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
   0.95]
 [ 0.    0.    0.    0.    0.    0.    0.   -0.95  0.    0.    0.    0.
   0.95]
 [ 0.    0.   -0.95 -0.95  0.    0.    0.    0.   -0.95  0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.   -0.95
   0.95]
 [ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.95  0.
   0.95]
 [ 0.    0.    0.    0.   